name: Deploy to Github Pages


on:
  push:
    branches: source

  workflow_dispatch:
  repository_dispatch:


jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install wheel
        pip install jupyter-book

    - name: Build the book
      run: jb build .

    - name: Archive artifact
      shell: sh
      if: runner.os == 'Linux'
      run: |
        chmod -c -R +rX . | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
        tar \
          --dereference --hard-dereference \
          --directory "_build/html" \
          -cvf "$RUNNER_TEMP/artifact.tar" \
          --exclude=.git \
          --exclude=.github \
          .

    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.6
      with:
        name: 'github-pages'
        path: ${{ runner.temp }}/artifact.tar
        retention-days: "1"

  deploy-pages:
    needs: build-book

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    - name: Deploy to Github Pages
      uses: actions/deploy-pages@v1
      id: deployment
