name: Deploy to Github Pages


on:
  push:
    branches: master

  workflow_dispatch:
  repository_dispatch:


jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install pipenv
        pipenv install --dev

    - name: Build the book
      run: pipenv run jb build .

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1.0.6
      with:
        name: 'github-pages'
        path: "_build/html"
        retention-days: "1"

  deploy-pages:
    needs: build-book

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Github Pages
      uses: actions/deploy-pages@v1.2.3
      id: deployment
